summary: Path used to manage the list of Hosts.
description: >-
  The REST endpoint/path used to list and create zero or more `Host` entities. 
  This path contains a `GET` and `POST` operation to perform the list and create
  tasks, respectively.
get:
  tags:
    - Hosts
  parameters:
    - name: query
      description: Will filter by `first_name`, `last_name`, and `email`
      schema:
        type: string
      in: query
    - name: limit
      description: Limits the results to a specified number, defaults to 50
      schema:
        type: integer
      in: query
    - name: offset
      description: Offsets the results to a specified number, defaults to 0
      schema:
        type: integer
      in: query
    - name: include
      description: A list of comma-separated related models to include
      schema:
        type: string
      in: query
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: ./models/PaginatedHostsList.v1.yaml
          examples:
            default:
              value:
                hosts:
                  - id: 71
                    email: some text
                    first_name: some text
                    last_name: some text
                    mobile_number: some text
                    profile_pic_url: some text
                  - id: 2
                    email: some text
                    first_name: some text
                    last_name: some text
                    mobile_number: some text
                    profile_pic_url: some text
                pagination:
                  total_records: 14
                  current_offset: 41
                  next_offset: 85
      description: Successful response - returns an array of `Host` entities.
    '400':
      content:
        application/json:
          schema:
            $ref: ./models/ErrorsList.v1.yaml
          examples:
            default:
              value:
                errors:
                  - domain: some text
                    attribute: some text
                    code: some text
                    message: some text
                  - domain: some text
                    attribute: some text
                    code: some text
                    message: some text
      description: A generic error
    '401':
      description: You don't have permission to view these Hosts
    '403':
      description: You do not have permission for this action
  operationId: getHosts
  summary: List all Hosts
  description: Gets a list of all `Host` entities.
post:
  requestBody:
    content:
      application/json:
        schema:
          $ref: ./models/HostCreateParams.v1.yaml
        examples:
          default:
            value:
              email: some text
              first_name: some text
              last_name: some text
              profile_pic_url: some text
              department: some text
              mobile_number: some text
    required: true
  tags:
    - Hosts
  parameters:
    - $ref: ../components/parameters/idempotencyKey.yml
  responses:
    '201':
      content:
        application/json:
          schema:
            $ref: ./models/Host.v1.yaml
          examples:
            default:
              value:
                id: 1
                email: some text
                first_name: some text
                last_name: some text
                profile_pic_url: some text
                department: some text
                mobile_number: some text
      description: Successful response
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: ./models/ErrorsList.v1.yaml
  operationId: createHost
  summary: Create a Host
  description: Creates a Host
