extends: spectral:oas
rules:
  tag-description: error
  enforce-snake-paths:
    description: Paths should use snakecase
    message: "The path '{{property}}' can't use camelCase or hyphens"
    type: style
    given: "$.paths[*]~"
    severity: error
    then:
      function: pattern
      functionOptions:
        notMatch: "[A-Z-]"
  enforce-content-format:
    description: Examples should be in application/json
    message: "You can only use the application/json format"
    type: style
    given: "$..content.*~"
    severity: warn
    then:
      function: pattern
      functionOptions:
        match: "json$"
  validate-operation-ids:
    description: Ensures consistency of operationId values
    message: "All operationIds should be in lowerCamelCase"
    type: style
    given: "$..operationId"
    severity: error
    then:
      function: casing
      functionOptions:
        type: camel