language: java
git:
  depth: false
branches:
  except:
    - /^*-v[0-9]/
  only:
    - master

before_install:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - sudo easy_install pip
  - pip install shyaml --user
  - source ./build-scripts/prepare_environment.sh

script:
  - ./openapi-generator.sh validate -i openapi.yml

before_deploy:
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q  --tags

deploy:
  skip_cleanup: true
  provider: releases
