language: java
git:
  depth: false
branches:
  only:
  - master

before_install:
  - sudo easy_install pip
  - pip install shyaml --user

script:
  - ./openapi-generator.sh validate -i openapi.yml
  - export API_VERSION=`cat openapi.yml | shyaml get-value info.version`
  - ./build-scripts/dart.sh