language: java
git:
  depth: false
branches:
  except:
    - /^*v[0-9]/
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_e0eab208aa27_key -iv $encrypted_e0eab208aa27_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - sudo easy_install pip
  - pip install shyaml --user
  - source ./build-scripts/prepare_environment.sh

script:
  - ./openapi-generator.sh validate -i openapi.yml
  - ./build-scripts/dart.sh
  - export GIT_TAG=v$API_VERSION
  - git commit -m "Generated SDK verion $API_VERSION from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q git@github.com:tractionguest/guest-api.git --follow-tags
