language: java
git:
  depth: false
branches:
  except:
    - /^v[0-9]/

before_install:
  - openssl aes-256-cbc -K $encrypted_e0eab208aa27_key -iv $encrypted_e0eab208aa27_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - sudo easy_install pip
  - pip install shyaml --user
  - source ./build-scripts/prepare_environment.sh
  - npm install -g redoc-cli
  - npm install speccy -g

script:
  - ./openapi-generator.sh validate -i openapi.yml
  - ./build-scripts/dart.sh
  - ./build-scripts/typescript-angular.sh
  - ./build-scripts/swift.sh
  - ./build-scripts/objc.sh
  - ./build-scripts/android.sh
  - ./build-scripts/redoc.sh
 
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then bash build-scripts/git.sh; fi'