language: java
git:
  depth: false
branches:
  only:
  - master

before_install:
  - sudo easy_install pip
  - pip install shyaml --user
  - source ./build-scripts/prepare_environment.sh

script:
  - ./openapi-generator.sh validate -i openapi.yml
  - ./build-scripts/dart.sh