summary: Path used to manage the list of Invites.
description: >-
    The REST endpoint/path used to list and create zero or more `Invite` entities.  This path contains a `GET`
    and `POST` operation to perform the list and create tasks, respectively.
get:
    tags:
        - Invites
    summary: List All Invites
    description: Gets a list of all `Invite` entities.
    operationId: getInvites
    parameters:
        -
            name: limit
            in: query
            description: 'Limits the results to a specified number, defaults to 50'
            schema:
                type: integer
        -
            name: offset
            in: query
            description: 'Offsets the results to a specified number, defaults to 0'
            schema:
                type: integer
        -
            name: query
            in: query
            description: 'Filters by `first_name`, `last_name`, `company`, and `email`'
            schema:
                type: string
        -
            name: with_colours
            in: query
            description: |-
                A comma separated list of case-insensitive colour values.

                i.e., `red`, `green`, `yellow`, and `orange`
            schema:
                type: string
        -
            name: location_ids
            in: query
            description: A comma separated list of Location IDs
            schema:
                type: integer
        -
            name: sort_by
            in: query
            description: Sorts by the field name and direction provided where the pattern is `FIELD_NAME_DIRECTION`
            schema:
                enum:
                    - start_date_asc
                    - start_date_desc
                    - end_date_asc
                    - end_date_desc
                    - created_at_asc
                    - created_at_desc
                    - updated_at_asc
                    - updated_at_desc
        -
            name: starts_before
            in: query
            description: Filters results to all those *before* the provided datetime
            schema:
                format: date
                type: string
        -
            name: starts_after
            in: query
            description: Filters results to all those *after* the provided datetime
            schema:
                format: date
                type: string
    responses:
        '200':
            description: Successful response - returns an array of `Invite` entities.
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/PaginatedInvitesList'
                    examples:
                        default:
                            value:
                                pagination:
                                    total_records: 10
                                    current_offset: 14
                                    next_offset: 16
                                invites:
                                    -
                                        id: 20
                                        first_name: some text
                                        last_name: some text
                                        start_date: '2018-02-10T09:30Z'
                                        location:
                                            id: 66
                                            name: some text
                                        watchlist:
                                            id: 37
                                            external_colours:
                                                - some text
                                                - some text
                                            internal_colours:
                                                - some text
                                                - some text
                                        watchlist_colour: {}
                                        hosts:
                                            -
                                                id: 35
                                                email: some text
                                                first_name: some text
                                                last_name: some text
                                                mobile: some text
                                                profile_pic_url: some text
                                            -
                                                id: 47
                                                email: some text
                                                first_name: some text
                                                last_name: some text
                                                mobile: some text
                                                profile_pic_url: some text
                                    -
                                        id: 46
                                        first_name: some text
                                        last_name: some text
                                        start_date: '2018-02-10T09:30Z'
                                        location:
                                            id: 29
                                            name: some text
                                        watchlist:
                                            id: 49
                                            external_colours:
                                                - some text
                                                - some text
                                            internal_colours:
                                                - some text
                                                - some text
                                        watchlist_colour: {}
                                        hosts:
                                            -
                                                id: 81
                                                email: some text
                                                first_name: some text
                                                last_name: some text
                                                mobile: some text
                                                profile_pic_url: some text
                                            -
                                                id: 32
                                                email: some text
                                                first_name: some text
                                                last_name: some text
                                                mobile: some text
                                                profile_pic_url: some text
                        Full List:
                            value:
                                invites:
                                    -
                                        id: 189
                                        first_name: Kenny G
                                        last_name: Mosciski
                                        start_date: '2019-07-07T16:00:00Z'
                                        watchlist_colour: RED
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 189
                                            external_colours: []
                                            internal_colours:
                                                - RED
                                    -
                                        id: 188
                                        first_name: Chandra
                                        last_name: Streich
                                        start_date: '2019-07-07T15:00:00Z'
                                        watchlist_colour: YELLOW
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 188
                                            external_colours: []
                                            internal_colours:
                                                - YELLOW
                                    -
                                        id: 187
                                        first_name: Shana
                                        last_name: Leffler
                                        start_date: '2019-07-07T14:00:00Z'
                                        watchlist_colour: ORANGE
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 187
                                            external_colours: []
                                            internal_colours:
                                                - ORANGE
                                    -
                                        id: 186
                                        first_name: Barney
                                        last_name: Weimann
                                        start_date: '2019-07-07T13:00:00Z'
                                        watchlist_colour: ORANGE
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 186
                                            external_colours: []
                                            internal_colours:
                                                - ORANGE
                                    -
                                        id: 185
                                        first_name: Neal
                                        last_name: Satterfield
                                        start_date: '2019-07-07T12:00:00Z'
                                        watchlist_colour: ORANGE
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 185
                                            external_colours: []
                                            internal_colours:
                                                - ORANGE
                                    -
                                        id: 184
                                        first_name: Hyun
                                        last_name: Kulas
                                        start_date: '2019-07-07T11:00:00Z'
                                        watchlist_colour: RED
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 184
                                            external_colours: []
                                            internal_colours:
                                                - RED
                                    -
                                        id: 183
                                        first_name: Cruz
                                        last_name: Kreiger
                                        start_date: '2019-07-07T10:00:00Z'
                                        watchlist_colour: ORANGE
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 183
                                            external_colours: []
                                            internal_colours:
                                                - ORANGE
                                    -
                                        id: 182
                                        first_name: Saturnina
                                        last_name: Hills
                                        start_date: '2019-07-07T09:00:00Z'
                                        watchlist_colour: ORANGE
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 182
                                            external_colours: []
                                            internal_colours:
                                                - ORANGE
                                    -
                                        id: 181
                                        first_name: Leana
                                        last_name: Jast
                                        start_date: '2019-07-07T08:00:00Z'
                                        watchlist_colour: YELLOW
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 181
                                            external_colours: []
                                            internal_colours:
                                                - YELLOW
                                    -
                                        id: 180
                                        first_name: Kayla
                                        last_name: Funk
                                        start_date: '2019-07-06T16:00:00Z'
                                        watchlist_colour: ORANGE
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 180
                                            external_colours: []
                                            internal_colours:
                                                - ORANGE
                                    -
                                        id: 179
                                        first_name: Lacie
                                        last_name: Ortiz
                                        start_date: '2019-07-06T15:00:00Z'
                                        watchlist_colour: YELLOW
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 179
                                            external_colours: []
                                            internal_colours:
                                                - YELLOW
                                    -
                                        id: 178
                                        first_name: Gearldine
                                        last_name: Kemmer
                                        start_date: '2019-07-06T14:00:00Z'
                                        watchlist_colour: ORANGE
                                        location:
                                            id: 1
                                            name: Default
                                        invite_watchlist:
                                            id: 178
                                            external_colours: []
                                            internal_colours:
                                                - ORANGE
                                pagination:
                                    total_records: 190
                                    current_offset: 0
                                    next_offset: 12
                                    limit: 12
