version: 2
jobs:
  validate:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # - run:
      #     name: Danger
      #     command: yarn danger ci
      - run:
          name: Lint yaml file
          command: npx @stoplight/spectral lint openapi.yml -- --ruleset=.spectral.yml --fail-severity=warn

  build:
    docker:
      - image: circleci/openjdk:14-buster-node
    steps:
      - run:
          name: Setup git
          command: |
            git config --global user.email "builds@circleci.com"
            git config --global user.name "CircleCI"
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt-get install python-setuptools
            sudo easy_install pip
            pip install shyaml --user
            source ./build-scripts/prepare_environment.sh
            npm install -g redoc-cli
            npm install speccy -g
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bc:f2:95:a1:42:cb:da:32:dd:2d:fe:5c:db:4a:f6:52"
      - run:
          name: Validate
          command: ./openapi-generator.sh validate -i openapi.yml
      - run:
          name: Clear generated content
          command: |
            rm -rf guest-*-sdk
            rm -rf docs/index.html
      - run:
          name: Build Dart
          command: ./build-scripts/dart.sh
      - run:
          name: Build TypeScript
          command: ./build-scripts/typescript-angular.sh
      - run:
          name: Build Swift
          command: ./build-scripts/swift.sh
      - run:
          name: Build ObjectiveC
          command: ./build-scripts/objc.sh
      - run:
          name: Build Android
          command: ./build-scripts/android.sh
      - run:
          name: Build documentation HTML
          command: ./build-scripts/redoc.sh
      - run:
          name: Deploy
          command: ./build-scripts/git.sh
workflows:
  version: 2

  validate_and_build:
    jobs:
      - validate:
          filters:
            branches:
              ignore:
                - /^v[0-9]/
      - build:
          requires:
            - validate
          filters:
            branches:
              ignore:
                - /^v[0-9]/
