version: 2
jobs:
  lint:
    docker:
      - image: 'stoplight/spectral'
    steps:
      - checkout
      - run:
          name: Lint Openapi Spec with docker
          command: spectral openapi.yml --ruleset=.spectral.yml --fail-severity=warn --verbose
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Danger
          command: yarn danger ci
      - run:
          name: Lint yaml file with npx
          command: npx @stoplight/spectral lint openapi.yml --ruleset=.spectral.yml --fail-severity=warn --verbose --skip-rule=oas3-valid-oas-content-example
      # Seems to work now, but is moot under their new system :|
      # - run:
      #     name: Publish docs
      #     command: npx @stoplight/cli@4 push --ci-token d57d5d93-0ea3-49f5-b87c-3b1b79993ac9 --url https://tractionguest.stoplight.io
workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - lint
