version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Lint yaml file
          command: npx @stoplight/spectral lint openapi.yml -- --ruleset=.spectral.yml --fail-severity=warn
      - run:
          name: Install stoplight CLI
          command: npm i --prefix=$HOME/.local -g @stoplight/cli
      - run:
          name: Publish docs
          command: stoplight publish --token {STOPLIGHT_API_KEY} --url https://stoplight.io/api
