version: 2
jobs:
  validate_yaml:
    docker:
      - image: 'stoplight/spectral'
    steps:
      - checkout
      - run:
          name: Lint Openapi Spec
          command: spectral lint openapi.yml --ruleset=.spectral.yml --fail-severity=warn --verbose --skip-rule=oas3-valid-oas-content-example
  validate_pr:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Danger
          command: yarn danger ci
  build:
    docker:
      - image: circleci/openjdk:16-jdk-buster-node
    steps:
      - run:
          name: Setup git
          command: |
            git config --global user.email "builds@circleci.com"
            git config --global user.name "CircleCI"
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install shyaml --user
            source ./build-scripts/prepare_environment.sh
            sudo npm install -g redoc-cli
            sudo npm install speccy -g
      - run:
          name: Validate
          command: ./openapi-generator.sh validate -i openapi.yml
      - run:
          name: Clear generated content
          command: |
            rm -rf guest-*-sdk
            rm -rf docs/index.html
      - run:
          name: Build & deplpoy SDKs
          command: ./build-scripts/generate_sdks.sh
      - run:
          name: Build documentation HTML
          command: ./build-scripts/redoc.sh
      - run:
          name: Deploy
          command: ./build-scripts/git.sh .
workflows:
  version: 2
  validate_and_build:
    jobs:
      # - validate_pr:
      #     filters:
      #       branches:
      #         ignore:
      #           - /^v[0-9]/
      - validate_yaml:
          filters:
            branches:
              ignore:
                - /^v[0-9]/
      - build:
          requires:
            - validate_yaml
          filters:
            branches:
              ignore:
                - /^v[0-9]/
