version: 2
jobs:
  lint:
    docker:
      - image: 'stoplight/spectral'
    steps:
      - checkout
      - run:
          name: Lint Openapi Spec with docker
          command: spectral lint openapi.yml --ruleset=.spectral.yml --fail-severity=warn --verbose
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Danger
          command: yarn danger ci
workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - lint
