name: GuestSDK
targets:
  GuestSDK:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [GuestSDK]
    info:
      path: ./Info.plist
      version: 0.13.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: Alamofire
