//
// Docusign.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Docusign: Codable { 


    public var templateId: String?
    public var integration: String?
    public var ndaStatus: String?
    public var ndaSignedDate: Date?
    public var envelopeId: String?
    public var sequence: String?
    public var docusignId: String?
    public var docusignName: String?
    public var title: String?

    public init(templateId: String?, integration: String?, ndaStatus: String?, ndaSignedDate: Date?, envelopeId: String?, sequence: String?, docusignId: String?, docusignName: String?, title: String?) {
        self.templateId = templateId
        self.integration = integration
        self.ndaStatus = ndaStatus
        self.ndaSignedDate = ndaSignedDate
        self.envelopeId = envelopeId
        self.sequence = sequence
        self.docusignId = docusignId
        self.docusignName = docusignName
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case templateId = "template_id"
        case integration
        case ndaStatus = "nda_status"
        case ndaSignedDate = "nda_signed_date"
        case envelopeId = "envelope_id"
        case sequence
        case docusignId = "docusign_id"
        case docusignName = "docusign_name"
        case title
    }

}
