//
// GuestAlertCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  */
public struct GuestAlertCreateParams: Codable { 


    public var signinSelectors: GuestAlertSigninSelectors?
    /** Specify the broadcast channel, one of &#39;SMS&#39; and/or &#39;EMAIL&#39; */
    public var channels: [String]
    /** Plain text of the alert to be sent */
    public var message: String

    public init(signinSelectors: GuestAlertSigninSelectors?, channels: [String], message: String) {
        self.signinSelectors = signinSelectors
        self.channels = channels
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case signinSelectors = "signin_selectors"
        case channels
        case message
    }

}
