//
// GuestResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The data collected from the response on a Registration */
public struct GuestResponse: Codable { 


    /** UUID */
    public var id: String?
    /** Flex fields */
    public var customFields: [CustomField]?
    public var pageType: String?
    public var sequence: Int?
    /** Page title */
    public var title: String?

    public init(id: String?, customFields: [CustomField]?, pageType: String?, sequence: Int?, title: String?) {
        self.id = id
        self.customFields = customFields
        self.pageType = pageType
        self.sequence = sequence
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case customFields = "custom_fields"
        case pageType = "page_type"
        case sequence
        case title
    }

}
