//
// GuestAlertCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GuestAlertCreateParams: Codable { 


    /** Plain text of the alert to be sent */
    public var message: String
    /** Specify the broadcast channel, one of &#39;SMS&#39; and/or &#39;EMAIL&#39; */
    public var channels: [String]
    public var signinSelectors: GuestAlertSigninSelectors?

    public init(message: String, channels: [String], signinSelectors: GuestAlertSigninSelectors?) {
        self.message = message
        self.channels = channels
        self.signinSelectors = signinSelectors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case message
        case channels
        case signinSelectors = "signin_selectors"
    }

}
