//
// Invite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The root of the Invite type&#39;s schema. */
public struct Invite: Codable { 


    public enum WatchlistColour: String, Codable, CaseIterable {
        case red = "RED"
        case green = "GREEN"
        case yellow = "YELLOW"
        case orange = "ORANGE"
    }
    public var id: Int
    public var firstName: String
    public var lastName: String
    public var startDate: Date?
    public var location: Location?
    public var watchlistColour: WatchlistColour?
    public var hosts: [Host]?
    public var inviteWatchlist: InviteWatchlist?
    public var endDate: Date?
    public var email: String
    public var mobileNumber: String?

    public init(id: Int, firstName: String, lastName: String, startDate: Date?, location: Location?, watchlistColour: WatchlistColour?, hosts: [Host]?, inviteWatchlist: InviteWatchlist?, endDate: Date?, email: String, mobileNumber: String?) {
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.startDate = startDate
        self.location = location
        self.watchlistColour = watchlistColour
        self.hosts = hosts
        self.inviteWatchlist = inviteWatchlist
        self.endDate = endDate
        self.email = email
        self.mobileNumber = mobileNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case firstName = "first_name"
        case lastName = "last_name"
        case startDate = "start_date"
        case location
        case watchlistColour = "watchlist_colour"
        case hosts
        case inviteWatchlist = "invite_watchlist"
        case endDate = "end_date"
        case email
        case mobileNumber = "mobile_number"
    }

}
