//
// PaginatedWatchlistList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedWatchlistList: Codable { 


    public var watchlists: [Watchlist]
    public var pagination: Pagination

    public init(watchlists: [Watchlist], pagination: Pagination) {
        self.watchlists = watchlists
        self.pagination = pagination
    }

}
