//
// PaginatedLocationsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedLocationsList: Codable { 


    public var pagination: Pagination
    public var locations: [Location]

    public init(pagination: Pagination, locations: [Location]) {
        self.pagination = pagination
        self.locations = locations
    }

}
