//
// PaginatedLocationsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PaginatedLocationsList: Codable { 


    public var locations: [Location]
    public var pagination: Pagination

    public init(locations: [Location], pagination: Pagination) {
        self.locations = locations
        self.pagination = pagination
    }

}
