//
// SigninUpdateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SigninUpdateParams: Codable { 


    /** Used to sign out the &#x60;Signin&#x60;, can only be set to &#x60;true&#x60;. */
    public var isSignedOut: Bool?
    /** Used to acknowledge the &#x60;Signin&#x60;, can only be set to &#x60;true&#x60;. */
    public var isAcknowledged: Bool?
    /** Used when keeping track of people in emergency situations */
    public var isAccountedFor: Bool?

    public init(isSignedOut: Bool?, isAcknowledged: Bool?, isAccountedFor: Bool?) {
        self.isSignedOut = isSignedOut
        self.isAcknowledged = isAcknowledged
        self.isAccountedFor = isAccountedFor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isSignedOut = "is_signed_out"
        case isAcknowledged = "is_acknowledged"
        case isAccountedFor = "is_accounted_for"
    }

}
