//
// SigninCreateParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Params used to create a Signin */
public struct SigninCreateParams: Codable { 


    public var guestEmailTemplateId: Int?
    public var hostEmailTemplateId: Int?
    /** Array of Host ids, ignored if &#x60;registration_id&#x60; is included */
    public var hostIds: [Int]?
    /** ID of the Location where the Signin happened, ignored if &#x60;registration_id&#x60; is included */
    public var locationId: Int?
    /** Should send notification to host/guests? */
    public var sendNotifications: Bool?
    public var smsMessage: String?
    /** First name, ignored if &#x60;registration_id&#x60; is included */
    public var firstName: String?
    /** Last name, ignored if &#x60;registration_id&#x60; is included */
    public var lastName: String?
    /** Company name, ignored if &#x60;registration_id&#x60; is included */
    public var company: String?
    /** E-mail, ignored if &#x60;registration_id&#x60; is included */
    public var email: String?
    /** UUID of a Registration */
    public var registrationId: String?

    public init(guestEmailTemplateId: Int?, hostEmailTemplateId: Int?, hostIds: [Int]?, locationId: Int?, sendNotifications: Bool?, smsMessage: String?, firstName: String?, lastName: String?, company: String?, email: String?, registrationId: String?) {
        self.guestEmailTemplateId = guestEmailTemplateId
        self.hostEmailTemplateId = hostEmailTemplateId
        self.hostIds = hostIds
        self.locationId = locationId
        self.sendNotifications = sendNotifications
        self.smsMessage = smsMessage
        self.firstName = firstName
        self.lastName = lastName
        self.company = company
        self.email = email
        self.registrationId = registrationId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case guestEmailTemplateId = "guest_email_template_id"
        case hostEmailTemplateId = "host_email_template_id"
        case hostIds = "host_ids"
        case locationId = "location_id"
        case sendNotifications = "send_notifications"
        case smsMessage = "sms_message"
        case firstName = "first_name"
        case lastName = "last_name"
        case company
        case email
        case registrationId = "registration_id"
    }

}
