//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The root of the User type&#39;s schema. */
public struct User: Codable { 


    public var id: Int
    public var firstName: String?
    public var lastName: String?
    public var email: String
    public var permissionGroups: [PermissionGroup]?
    /** Identifies if user has access to mobile app features. */
    public var mobileAccessEnabled: Bool

    public init(id: Int, firstName: String?, lastName: String?, email: String, permissionGroups: [PermissionGroup]?, mobileAccessEnabled: Bool) {
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.permissionGroups = permissionGroups
        self.mobileAccessEnabled = mobileAccessEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case firstName = "first_name"
        case lastName = "last_name"
        case email
        case permissionGroups = "permission_groups"
        case mobileAccessEnabled = "mobile_access_enabled"
    }

}
