/**
 * Traction Guest API
 * The leader in enterprise visitor management, empowers businesses across five continents and dozens of industries to keep people safe while creating connection in the contactless world.
 *
 * The version of the OpenAPI document: 0.11.11
 * Contact: bmckay@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.User;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * 
 **/
@ApiModel(description = "")
public class BatchJob {
  
  @SerializedName("bid")
  private String bid = null;
  @SerializedName("created_at")
  private String createdAt = null;
  @SerializedName("status")
  private String status = null;
  @SerializedName("total_records")
  private Integer totalRecords = null;
  @SerializedName("worker_name")
  private String workerName = null;
  @SerializedName("user")
  private User user = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getBid() {
    return bid;
  }
  public void setBid(String bid) {
    this.bid = bid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getTotalRecords() {
    return totalRecords;
  }
  public void setTotalRecords(Integer totalRecords) {
    this.totalRecords = totalRecords;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWorkerName() {
    return workerName;
  }
  public void setWorkerName(String workerName) {
    this.workerName = workerName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public User getUser() {
    return user;
  }
  public void setUser(User user) {
    this.user = user;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchJob batchJob = (BatchJob) o;
    return (this.bid == null ? batchJob.bid == null : this.bid.equals(batchJob.bid)) &&
        (this.createdAt == null ? batchJob.createdAt == null : this.createdAt.equals(batchJob.createdAt)) &&
        (this.status == null ? batchJob.status == null : this.status.equals(batchJob.status)) &&
        (this.totalRecords == null ? batchJob.totalRecords == null : this.totalRecords.equals(batchJob.totalRecords)) &&
        (this.workerName == null ? batchJob.workerName == null : this.workerName.equals(batchJob.workerName)) &&
        (this.user == null ? batchJob.user == null : this.user.equals(batchJob.user));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.bid == null ? 0: this.bid.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.status == null ? 0: this.status.hashCode());
    result = 31 * result + (this.totalRecords == null ? 0: this.totalRecords.hashCode());
    result = 31 * result + (this.workerName == null ? 0: this.workerName.hashCode());
    result = 31 * result + (this.user == null ? 0: this.user.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchJob {\n");
    
    sb.append("  bid: ").append(bid).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  status: ").append(status).append("\n");
    sb.append("  totalRecords: ").append(totalRecords).append("\n");
    sb.append("  workerName: ").append(workerName).append("\n");
    sb.append("  user: ").append(user).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
