/**
 * Traction Guest API
 * The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.  # Getting Started If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).  We will also add you to our Slack channel where you can ask questions and get further help.  # Terms and Conditions Please visit: [https://tractionguest.com/tos/api/](https://tractionguest.com/tos/api/)  # Versioning This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.  * The `Major` number increments when potentially incompatible changes are made. * The `Minor` number increments when backwards-compatible additions are made. * The `Patch` number increments when backwards-compatible bug-fixes are made. 
 *
 * The version of the OpenAPI document: 0.13.0
 * Contact: support@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.GuestAlertSigninSelectors;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * 
 **/
@ApiModel(description = "")
public class GuestAlertCreateParams {
  
  @SerializedName("signin_selectors")
  private GuestAlertSigninSelectors signinSelectors = null;
  @SerializedName("channels")
  private List<String> channels = null;
  @SerializedName("message")
  private String message = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public GuestAlertSigninSelectors getSigninSelectors() {
    return signinSelectors;
  }
  public void setSigninSelectors(GuestAlertSigninSelectors signinSelectors) {
    this.signinSelectors = signinSelectors;
  }

  /**
   * Specify the broadcast channel, one of 'SMS' and/or 'EMAIL'
   **/
  @ApiModelProperty(required = true, value = "Specify the broadcast channel, one of 'SMS' and/or 'EMAIL'")
  public List<String> getChannels() {
    return channels;
  }
  public void setChannels(List<String> channels) {
    this.channels = channels;
  }

  /**
   * Plain text of the alert to be sent
   **/
  @ApiModelProperty(required = true, value = "Plain text of the alert to be sent")
  public String getMessage() {
    return message;
  }
  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GuestAlertCreateParams guestAlertCreateParams = (GuestAlertCreateParams) o;
    return (this.signinSelectors == null ? guestAlertCreateParams.signinSelectors == null : this.signinSelectors.equals(guestAlertCreateParams.signinSelectors)) &&
        (this.channels == null ? guestAlertCreateParams.channels == null : this.channels.equals(guestAlertCreateParams.channels)) &&
        (this.message == null ? guestAlertCreateParams.message == null : this.message.equals(guestAlertCreateParams.message));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.signinSelectors == null ? 0: this.signinSelectors.hashCode());
    result = 31 * result + (this.channels == null ? 0: this.channels.hashCode());
    result = 31 * result + (this.message == null ? 0: this.message.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GuestAlertCreateParams {\n");
    
    sb.append("  signinSelectors: ").append(signinSelectors).append("\n");
    sb.append("  channels: ").append(channels).append("\n");
    sb.append("  message: ").append(message).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
