#import <Foundation/Foundation.h>
#import "TGObject.h"

/**
* Traction Guest API
* The leader in enterprise visitor management, empowers businesses across five continents and dozens of industries to keep people safe while creating connection in the contactless world.
*
* The version of the OpenAPI document: 0.11.6
* Contact: bmckay@tractionguest.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "TGFlexField.h"
@protocol TGFlexField;
@class TGFlexField;



@protocol TGGuestResponse
@end

@interface TGGuestResponse : TGObject

/* UUID [optional]
 */
@property(nonatomic) NSString* _id;
/* Flex fields [optional]
 */
@property(nonatomic) NSArray<TGFlexField>* customFields;
/* Enum [optional]
 */
@property(nonatomic) NSString* pageType;

@property(nonatomic) NSNumber* sequence;
/* Page title [optional]
 */
@property(nonatomic) NSString* title;

@end
