#import <Foundation/Foundation.h>
#import "TGObject.h"

/**
* Traction Guest API
* A compelling story about a lone device, on a quest for its data.
*
* The version of the OpenAPI document: 0.11.3
* Contact: bmckay@tractionguest.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "TGHost.h"
#import "TGInviteWatchlist.h"
#import "TGLocation.h"
#import "TGRegistration.h"
@protocol TGHost;
@class TGHost;
@protocol TGInviteWatchlist;
@class TGInviteWatchlist;
@protocol TGLocation;
@class TGLocation;
@protocol TGRegistration;
@class TGRegistration;



@protocol TGInvite
@end

@interface TGInvite : TGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSDate* startDate;

@property(nonatomic) TGLocation* location;

@property(nonatomic) NSString* watchlistColour;

@property(nonatomic) NSArray<TGHost>* hosts;

@property(nonatomic) TGInviteWatchlist* inviteWatchlist;

@property(nonatomic) NSDate* endDate;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* mobileNumber;

@property(nonatomic) TGRegistration* registration;

@end
