#import <Foundation/Foundation.h>
#import "TGObject.h"

/**
* Traction Guest API
* A compelling story about a lone device, on a quest for its data.
*
* The version of the OpenAPI document: 0.11.4
* Contact: bmckay@tractionguest.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol TGInternalWatchlistResult
@end

@interface TGInternalWatchlistResult : TGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) NSString* email;

@property(nonatomic) NSString* colour;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* firstName;

@end
