#import <Foundation/Foundation.h>
#import "TGObject.h"

/**
* Traction Guest API
* The leader in enterprise visitor management, empowers businesses across five continents and dozens of industries to keep people safe while creating connection in the contactless world.
*
* The version of the OpenAPI document: 0.11.9
* Contact: bmckay@tractionguest.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "TGGroupVisit.h"
#import "TGHost.h"
#import "TGInviteWatchlist.h"
#import "TGLocation.h"
#import "TGRegistration.h"
@protocol TGGroupVisit;
@class TGGroupVisit;
@protocol TGHost;
@class TGHost;
@protocol TGInviteWatchlist;
@class TGInviteWatchlist;
@protocol TGLocation;
@class TGLocation;
@protocol TGRegistration;
@class TGRegistration;



@protocol TGInvite
@end

@interface TGInvite : TGObject


@property(nonatomic) NSNumber* _id;

@property(nonatomic) TGRegistration* registration;
/*  [optional]
 */
@property(nonatomic) NSString* mobileNumber;
/*  
 */
@property(nonatomic) NSString* email;
/*  [optional]
 */
@property(nonatomic) NSDate* endDate;

@property(nonatomic) TGInviteWatchlist* inviteWatchlist;

@property(nonatomic) NSArray<TGHost>* hosts;

@property(nonatomic) NSString* watchlistColour;

@property(nonatomic) TGLocation* location;

@property(nonatomic) NSDate* startDate;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* firstName;

@property(nonatomic) TGGroupVisit* groupVisit;

@end
