#import <Foundation/Foundation.h>
#import "TGObject.h"

/**
* Traction Guest API
* A compelling story about a lone device, on a quest for its data.
*
* The version of the OpenAPI document: 0.11.2
* Contact: bmckay@tractionguest.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "TGAuditLog.h"
#import "TGPagination.h"
@protocol TGAuditLog;
@class TGAuditLog;
@protocol TGPagination;
@class TGPagination;



@protocol TGPaginatedAuditLogsList
@end

@interface TGPaginatedAuditLogsList : TGObject


@property(nonatomic) NSArray<TGAuditLog>* auditLogs;

@property(nonatomic) TGPagination* pagination;

@end
