#import <Foundation/Foundation.h>
#import "TGObject.h"

/**
* Traction Guest API
* The Traction Guest API is currently under limited release to select customers as we gather and iterate on feedback.  # Getting Started If you are interested in getting early access to the API, please send us an email to [support@tractionguest.com](mailto:support@tractionguest.com).  We will also add you to our Slack channel where you can ask questions and get further help.  # Terms and Conditions Please visit: [https://tractionguest.com/tos/api/](https://tractionguest.com/tos/api/)  # Versioning This API follows [semantic versioning](https://semver.org/), which follows the `Major`.`Minor`.`Patch` format.  * The `Major` number increments when potentially incompatible changes are made. * The `Minor` number increments when backwards-compatible additions are made. * The `Patch` number increments when backwards-compatible bug-fixes are made. 
*
* The version of the OpenAPI document: 0.13.0
* Contact: support@tractionguest.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "TGPermissionGroup.h"
@protocol TGPermissionGroup;
@class TGPermissionGroup;



@protocol TGUser
@end

@interface TGUser : TGObject


@property(nonatomic) NSNumber* _id;
/* Identifies if user has access to mobile app features. 
 */
@property(nonatomic) NSNumber* mobileAccessEnabled;

@property(nonatomic) NSArray<TGPermissionGroup>* permissionGroups;
/*  
 */
@property(nonatomic) NSString* email;
/*  [optional]
 */
@property(nonatomic) NSString* lastName;
/* Determines if the registration portal has been enabled for this account [optional]
 */
@property(nonatomic) NSString* firstName;
/* Determines if the registration portal has been enabled for this account 
 */
@property(nonatomic) NSNumber* registrationPortalEnabled;

@end
