/**
 * Traction Guest API
 * A compelling story about a lone device, on a quest for its data.
 *
 * The version of the OpenAPI document: 0.11.1
 * Contact: bmckay@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomFieldGuest } from './customField';
import { NotificationTriggerCreateParamsGuest } from './notificationTriggerCreateParams';


/**
 * The root of the InviteCreateParams type\'s schema.
 */
export interface InviteCreateParamsGuest { 
    company?: string;
    email: string;
    endDate?: Date;
    lastName: string;
    /**
     * The `start_date` is required for invitations to lobbies
     */
    startDate?: Date;
    title?: string;
    watchlistColour?: InviteCreateParamsGuest.WatchlistColourGuestEnum;
    hostIds?: Array<number>;
    customFields?: Array<CustomFieldGuest>;
    emailTemplateId?: number;
    firstName: string;
    notificationTriggers?: Array<NotificationTriggerCreateParamsGuest>;
    mobileNumber?: string;
}
export namespace InviteCreateParamsGuest {
    export type WatchlistColourGuestEnum = 'RED' | 'GREEN' | 'YELLOW' | 'ORANGE';
    export const WatchlistColourGuestEnum = {
        RED: 'RED' as WatchlistColourGuestEnum,
        GREEN: 'GREEN' as WatchlistColourGuestEnum,
        YELLOW: 'YELLOW' as WatchlistColourGuestEnum,
        ORANGE: 'ORANGE' as WatchlistColourGuestEnum
    };
}

