/**
 * Traction Guest API
 * A compelling story about a lone device, on a quest for its data.
 *
 * The version of the OpenAPI document: 0.11.4
 * Contact: bmckay@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExternalWatchlistResultGuest } from './externalWatchlistResult';
import { InternalWatchlistResultGuest } from './internalWatchlistResult';


/**
 * The root of the InviteWatchlist type\'s schema.
 */
export interface InviteWatchlistGuest { 
    id: number;
    /**
     * Deprecated
     */
    externalColours?: Array<string>;
    /**
     * Deprecated
     */
    internalColours?: Array<string>;
    external?: Array<ExternalWatchlistResultGuest>;
    internal?: Array<InternalWatchlistResultGuest>;
}

