/**
 * Traction Guest API
 * A compelling story about a lone device, on a quest for its data.
 *
 * The version of the OpenAPI document: 0.10.3
 * Contact: bmckay@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NotificationsHostFilterParamsGuest } from './notificationsHostFilterParams';
import { NotificationsSigninFilterParamsGuest } from './notificationsSigninFilterParams';


export interface NotificationsCreateParamsGuest { 
    /**
     * Notification body 
     */
    message: string;
    signinFilters?: NotificationsSigninFilterParamsGuest;
    /**
     * Specify the broadcast channel, such as \'SMS\' or \'EMAIL\'
     */
    channels: NotificationsCreateParamsGuest.ChannelsGuestEnum;
    hostFilters?: NotificationsHostFilterParamsGuest;
    /**
     * The type of object that will receive the notification such as, \'signin\' or \'host\'
     */
    target: NotificationsCreateParamsGuest.TargetGuestEnum;
}
export namespace NotificationsCreateParamsGuest {
    export type ChannelsGuestEnum = 'SMS' | 'EMAIL';
    export const ChannelsGuestEnum = {
        SMS: 'SMS' as ChannelsGuestEnum,
        EMAIL: 'EMAIL' as ChannelsGuestEnum
    };
    export type TargetGuestEnum = 'HOSTS' | 'SIGNINS';
    export const TargetGuestEnum = {
        HOSTS: 'HOSTS' as TargetGuestEnum,
        SIGNINS: 'SIGNINS' as TargetGuestEnum
    };
}

