/**
 * Traction Guest API
 * A compelling story about a lone device, on a quest for its data.
 *
 * The version of the OpenAPI document: 0.11.3
 * Contact: bmckay@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The root of the Pagination type\'s schema.
 */
export interface PaginationGuest { 
    totalRecords?: number;
    currentOffset?: number;
    nextOffset?: number;
    /**
     * The last ID rendered, if the request included the \'after_id\' param.
     */
    lastId?: number;
}

