/**
 * Traction Guest API
 * The leader in enterprise visitor management, empowers businesses across five continents and dozens of industries to keep people safe while creating connection in the contactless world.
 *
 * The version of the OpenAPI document: 0.11.10
 * Contact: bmckay@tractionguest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionGroupGuest } from './permissionGroup';


/**
 * The root of the User type\'s schema.
 */
export interface UserGuest { 
    id: number;
    /**
     * Identifies if user has access to mobile app features.
     */
    mobileAccessEnabled: boolean;
    permissionGroups?: Array<PermissionGroupGuest>;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    lastName?: string;
    /**
     * Determines if the registration portal has been enabled for this account
     */
    firstName?: string;
    /**
     * Determines if the registration portal has been enabled for this account
     */
    registrationPortalEnabled: boolean;
}

