name: Validate Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Danger
      uses: danger/danger-js@9.2.10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
